### ISSUE TITLE
 Schüler auflisten

### ISSUE THREAD

**Issue by FKINF16** [ServiceAsAService/angularClassbook#2]
Listenfenster:
- Liste aller Schüler anzeigen
- Schüler Löschen (mit Warnung)
- Link auf Bearbeitung des Schülers

**Comment by LeoDJ** [comment]
Geschlossen durch https://github.com/ServiceAsAService/angularClassbook/commit/21fac3384a7330cec4d0e6d65a7bcc83d8f0baef
