### ISSUE TITLE
Klassenliste

### ISSUE THREAD

**Issue by FKINF16** [ServiceAsAService/angularClassbook#3]
Listenfenster:

- Liste der Schüler in einer Klasse anzeigen **(Nicht zwingend)**
- Liste aller Klassen anzeigen
- Klasse Löschen (mit Warnung)
- _Liste kann Such- und Sortierfunktion beinhalten_

Klasse erstellen/bearbeiten:

- Name ändern
- _Schüler hinzufügen/entfernen (Liste der Schüler muss hierfür abgerufen werden)_
- Stufe ändern

Attribute der Klasse: Name, Stufe

**Comment by LeoDJ** [comment]
Hauptpunkte abgeschlossen durch https://github.com/ServiceAsAService/angularClassbook/commit/4bc1147bc65b7c86b70eb8795e79f9276df4a91f

Schüler werden durch die Schüleransicht einer Klasse zugeordnet.
